__all__ = ["RegisterHandler",
           "LoginHandler",
           "AuthenHandler",
           "LogoutHandler",
           "CancelHandler",
           "CheckrelativesHandler",
           "DeleterelativesHandler",
           "HistoryHandler",
           "HelpmessageHandler",
           "SupportmessageHandler",
           "FinishHandler",
           "GivecreditHandler",
           "AddaidHandler",
           "SendsupportHandler",
           "QuitaidHandler"]
